version: "3.7" # Compose file version

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    networks:
      - voo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - voo

  sisu:
    build:
      context: ./packages/database
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    networks:
      - voo

  next:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: voo-next-dev
    depends_on:
      database:
        condition: service_healthy
    networks:
      - voo
    volumes:
      - ./packages/frontend:/usr/src/app
    ports:
      - 3000:3000
volumes:
  # Database data
  db-data:

networks:
  # Nappikauppa network for development
  voo:
